export enum GeneratePasswordPropsEnum {
  LENGTH = 'length',
  USE_NUMBERS = 'useNumbers',
  USE_UPPERCASE = 'useUppercase',
  USE_LOWERCASE = 'useLowercase',
  USE_SYMBOLS = 'useSymbols',
  EXCLUDE_SIMILAR_CHARACTERS = 'excludeSimilarCharacters',
  EXCLUDE = 'exclude',
  COUNT = 'count',
  MIN_NUMBERS = 'minNumbers',
  MIN_UPPERCASE = 'minUppercase',
  MIN_LOWERCASE = 'minLowercase',
  MIN_SYMBOLS = 'minSymbols',
  CUSTOM_LOWERCASE = 'customLowercase',
  CUSTOM_UPPERCASE = 'customUppercase',
  CUSTOM_NUMBERS = 'customNumbers',
  CUSTOM_SYMBOLS = 'customSymbols',
}
